### ISSUE TITLE
zopen_init fails to finish

### ISSUE THREAD

**Issue by AmusedWaffle** [zopencommunity/dufport#2]
When zopen build gets to the "Running Configure" step, it's unable to load packages because "go list -json -e -mod=readonly ./duf" returns with an exit status of 1 with the error message: "go: could not create module cache: mkdir /home/waffle/go: EDC5141I Read-only file system."

`Applying patches
***WARNING: No patches in /waffle/zopen-data/boot/dufport/patches to apply
VERBOSE: 'Running zopen_init'
Skip Bootstrap
VERBOSE: 'bootstrap completed in 0 seconds.'
Running Configure
VERBOSE: '"zopen_wharf" --prefix=/home/waffle/zopen/prod/duf-master  >/tmp/WAFFLE.pipe 2>&1'
Backed up workspace to /waffle/zopen-data/boot/dufport/go.work.backup
unable to load packages: cmd: go list -json -e -mod=readonly ./duf: exit status 1
Porting failed due to errors mentioned above
VERBOSE: 'configure completed in 4 seconds.'
Running Build
VERBOSE: '"go" build > /tmp/WAFFLE.pipe 2>&1'
go: could not create module cache: mkdir /home/waffle/go: EDC5141I Read-only file system.
***ERROR: Make (minimal) failed. Log: /waffle/zopen-data/boot/dufport/log/20230714_142005_build.log
zopen-build completed in 14 seconds.`

**Comment by AmusedWaffle** [comment]
I think I just need to figure out the directory to set the GOPATH environment variable to

**Comment by IgorTodorovskiIBM** [comment]
That's interesting that it cannot create /home/waffle/go, might be a system issue. I'll check

**Comment by IgorTodorovskiIBM** [comment]
Ok, I had to create a symlink because of the disk space issue on /home/. It goes a bit further now

**Comment by AmusedWaffle** [comment]
Igor's symlink fixed the issue
